language: java
jdk:
- openjdk11
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew -i check"
deploy:
  provider: heroku
  api_key:
    secure: p3jmxQiLMv1r3SXXseif1N73Fy0zYVAUCZbjIZFFVWWG0oCsvBFfLVrlOD9L9FpvbGOke5JqOb9TozE96pEO1sVs1B2jFeji/AciCdspxOiK6E+WKrbpr7HVfQ5z3DaBR9tnHOumLkif85XfvDiL3TzqbRgJ+vwzgxvgL5yqIlrrav4iwVdICapMkHrvzZnKveMScetuskVqq4btoKPOIhp9GTNuKhxBw2BQ0PWrz4solqB++YEqr8eEjFHoYS76LYI1XjHNGMumzyEpJxbA9lhFhpDN31O1pWNgWqsObVxfedB9ObPXtVnyrLzsz7oyXt7tPlCL/oWB7TSkFQQPzJ3TBl/FQQvYhaZTcigIrjh5t2QkWRAXT/1j/P6HkRd6cVd68GOWWdwsPSJ7476RHlISO2RQRFno6zhyGJL3bkmeOZzcP2jl8NR7Al16h/wQQXA/s2HZEhH7WZ8Ryv9+wXGfH3JfOT4rMf9u/14GUfOoHePtiTXyuHnvDhrcF4JWoM8tMLPxdl5RApjYlZbk+I+Zf46Lwsl3cMKvVXqvKJSVt7wrc1UZuYoSkFjcEd6dgNDP7pGcIvEJ/XHal2V2hANo16Sh2+AVCQEHSrIcUpF6PzxF5rOw4wArxeXlkYNGnIfR68sUqi3yF5IkK2vyBz5EUIzgVT1h0CkxhP8AHQM=
